<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="itmo_oop_lab1.Tests\**\*.cs" />
    <None Remove="itmo_oop_lab1.Tests\**\*" />
    <EmbeddedResource Remove="itmo_oop_lab1.Tests\**\*" />
  </ItemGroup>

</Project>
